### ISSUE TITLE
Add support for Selenium Grid

### ISSUE THREAD

**Issue by rzo1** [apache/incubator-stormcrawler#1023]
Mainly creating this issue as a possible future request for anyone, who has some time to contribute.

Selenium nowadays supports [Selenium Grid ](https://www.selenium.dev/documentation/grid/). Selenium Grid runs in parallel on multiple machines (called Nodes) coordinated by a Hub instance.

Details can be found here: https://www.selenium.dev/documentation/grid/components/

Our current Selenium Protocol impl cannot deal with the Hub setting as we are using a `LinkedBlockingQueue` to handle multiple Selenium drivers (instances).

We should perhaps add an additional `SeleniumGridProtocol`, which can make use of Selenium Grid so we can fully leverage the grids distributed capabilities (instead using only one session of a given Selenium Grid)

**Comment by msghasan** [comment]
That's very much needed shall I try it on my weekend and try to give a upgrade

**Comment by rzo1** [comment]
> That's very much needed shall I try it on my weekend and try to give a upgrade

Sure. If you have some spare resources / time to work on it, feel free. A PR would be very much appreciated. 

The grid deals with the queue / sessions ids, so we would need to build some logic to handle that on our side. I wouldn't change the current Selenium impl, though to avoid breaking users (not every body uses a Selenium grid).

**Comment by dhaneshsabane** [comment]
Referencing the detailed discussion we've had on https://github.com/DigitalPebble/storm-crawler/discussions/1092, a separate implementation for Selenium Grid makes sense.

@rzo1 , @jnioche - Shall I pick this up and raise a PR?

**Comment by jnioche** [comment]
> @rzo1 , @jnioche - Shall I pick this up and raise a PR?

This would be great, thanks

**Comment by dhaneshsabane** [comment]
@jnioche - Feel free to assign this issue to me.

**Comment by msghasan** [comment]
I have the solution but being very busy nowadays,  I thought of pushing it long back and forgot to do it...

**Comment by msghasan** [comment]
I have pushed the solution to my fork. @jnioche @rzo1 Take a look if you feel the implementation is good to have let me know I will raise the PR. If not @dhaneshsabane  can take some inspiration and ideas to further enhance from this. I am extremely sorry to delay this so much. 

https://github.com/msghasan/storm-crawler/commit/4bfdba7ad737c19508ac5649eaf1174c7a31c9b8

**Comment by msghasan** [comment]
The changes produced  in my previous message was tested  in production environment and was getting used for our purpose.

**Comment by dhaneshsabane** [comment]
@msghasan - Thank you so much for sharing the implementation. I managed to deploy your changes to my server and get the setup working. However, I did have to make a couple of changes, primarily around how capabilities were set.

Do you want to raise this as a pull request @msghasan?

**Comment by rzo1** [comment]
So perhaps open a PR and collaborate in getting the required changes into that PR? ;-) Afterwards, we can do a review, etc.

**Comment by msghasan** [comment]
@rzo1  @jnioche  Please review the below PR and let me know your thoughts on this

https://github.com/DigitalPebble/storm-crawler/pull/1123

**Comment by msghasan** [comment]
[# PR Explanation](https://github.com/DigitalPebble/storm-crawler/pull/1123#issuecomment-1819585834)

**Comment by rzo1** [comment]
From my POV (and as original opener of this issue), we now have playwright available, which scales easily.  So I am going to close this.
