### ISSUE TITLE
Add support for Playwright

### ISSUE THREAD

**Issue by rzo1** [apache/incubator-stormcrawler#1024]
Mainly creating this issue as a possible future request for anyone, who has some time to contribute.

It would be neat to have Playwright protocol impl for SC.

Note, that Playwright can also connect to [Selenium Grid ](https://playwright.dev/docs/selenium-grid), which would make it a cool addition. 

Related: https://github.com/DigitalPebble/storm-crawler/issues/1023

**Comment by sebastian-nagel** [comment]
Actually, some work is already done in #899/#902

**Comment by rzo1** [comment]
Yup - saw the PRs 😎 - thanks for referencing them. Might be a good starting point.

**Comment by sam-ulrich1** [comment]
The existing work may be fully operational. The problem that stalled out the work was on playwrights side and since the API has not changed it is likely a simple upgrade would fix everything.

The crawler worked but playwright would crash after a couple thousand pages
