### ISSUE TITLE
can we rename the 'master' branch as 'main'?

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-stormcrawler#1156]
Just feels a bit better name wise. 'main' is now the default in GitHub.

**Comment by jnioche** [comment]
On my other repos I can see that this is done via _Settings -> General -> Default branches_ but now that it is at Apache, I don't have access to the Settings section.
Do we do it manually instead e.g. following https://www.git-tower.com/learn/git/faq/git-rename-master-to-main ?

**Comment by pjfanning** [comment]
We might need to raise an INFRA issue. They have full access. If we get agreement to proceed, I can raise the JIRA.

**Comment by rzo1** [comment]
Needs to be done bei INFRA ;-) (done that for a few ASF projects)

**Comment by pjfanning** [comment]
I raised https://issues.apache.org/jira/browse/INFRA-25661

**Comment by jnioche** [comment]
It has been done by infra.
