### ISSUE TITLE
Drop coveralls code-coverage flow?

### ISSUE THREAD

**Issue by rzo1** [apache/incubator-stormcrawler#1162]
Can we drop the coveralls github action? 

I did a quick search at ASF level and I think, that only datasketches-cpp is using it. So might be good to just drop it and rely on other test coverage report metrics, which are more common at ASF level.

**Comment by lewismc** [comment]
SonarCloud.io is very good.

**Comment by sigee** [comment]
Hi,
For checking and requiring a minimum test coverage you could use jacoco as it is used in [apache commons project](https://github.com/apache/commons-parent/blob/master/pom.xml#L218).

There is no generated badge for readme, but the pipeline could work perfectly by require a minimum coverage for different metrics (line coverage, branch coverage, class coverage, etc.).
Jacoco is already part of this project, so only the configuration is needed here.

What do you think?

**Comment by rzo1** [comment]
I am using Jacoco in most of my projects ;-) - I have no objections in replacing it.
