### ISSUE TITLE
Deal with non-open source version of Elasticsearch

### ISSUE THREAD

**Issue by jnioche** [apache/incubator-stormcrawler#1167]
As mentioned in the incubation [proposal](https://cwiki.apache.org/confluence/display/INCUBATOR/StormCrawler+Proposal)

`Most dependencies are ASFv2 licensed. There are possible concerns around the Elasticsearch dependencies (Elastic License 2.0 - not open source). We will address these either by downgrading the version of Elasticsearch to 7.10.2, which is under ASFv2, remove the Elastic module altogether or make the dependency optional and instruct the users on how to activate it themselves to avoid having this non ASLv2 compliant licence in the distributions.`

**Comment by rzo1** [comment]
+1 for downgrade (for now)

**Comment by jnioche** [comment]
I'd be in favour of removing it altogether. If downgraded, the code will never evolve and will be so out of sync with Elastic that it won't be useful.
the code of the Opensearch plugin is also better. If people want to use their Elastic indices, they should be able to find a matching version of OS

**Comment by rzo1** [comment]
I am ok with removing it but only if we provide some documentation for people / users on how to migrate existing indices / installation to the openserach plugin (and if it is just a README placed in the elastic search module folder pointing to existing open-search documentation). By doing so, we have a clear migration path and don't kill possible users.

**Comment by rzo1** [comment]
To follow up here: 

Maybe we just place a README.md in the module (after we removed the content) and refer to https://opensearch.org/docs/latest/upgrade-to/upgrade-to/ (people looking to upgrade to 3.0 will than see, that the module isn't available anymore and find some direct links on how to upgrade their elastic search stuff and switch to the open search module). We can remove that README in the next minor release following 3.0 ? wdyt?
