### ISSUE TITLE
change CONTRIBUTING.md

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-stormcrawler#1168]
The current file is out of date for an Apache podling.

I'm not sure what an updated file would say but it should probably mention that CLAs may be required for big changes.

https://www.apache.org/licenses/contributor-agreements.html

**Comment by rzo1** [comment]
We might find an answer along https://github.com/search?q=org%3Aapache%20CONTRIBUTING.md&type=code

**Comment by ayushtkn** [comment]
I think that DCO isn't required, & ICLA is also mandatory mostly for committers. I think this is a .md version of "How To Contribute"
maybe we can get some pointers from similar docs & incorporate them
https://cwiki.apache.org/confluence/display/HADOOP/How+To+Contribute
https://cwiki.apache.org/confluence/display/JCLOUDS/How+to+Contribute
https://cwiki.apache.org/confluence/display/FLUME/How+to+Contribute
https://cwiki.apache.org/confluence/display/SQOOP/How+to+Contribute
