### ISSUE TITLE
Close the Discord channel and move to #asf Slack

### ISSUE THREAD

**Issue by rzo1** [apache/incubator-stormcrawler#1171]
as the title says

We need to also update the README.

**Comment by jnioche** [comment]
the ASF slack is not open to the public AFAIK but only to ASF members

**Comment by rzo1** [comment]
Everyone can join the ASF slack. It just requires an invitation from an asf committer  :)

**Comment by jnioche** [comment]
> Everyone can join the ASF slack. It just requires an invitation from an asf committer :)

that's not super open. Do other projects at Apache have Discord channels outside Apache?

**Comment by pjfanning** [comment]
> > Everyone can join the ASF slack. It just requires an invitation from an asf committer :)
> 
> that's not super open. Do other projects at Apache have Discord channels outside Apache?

You can split the channels. Have internal team chats on Slack. Leave Discord there for other users.
I would suggest that GitHub discussions can be used to replace many of the Slack/Discord conversations. The GitHub discussion keeps everything related to a given discussion together while Slack/Discord can be a pain if there are multiple concurrent discussions.

**Comment by jnioche** [comment]
I also prefer Discussions. I will close Discord soon and remove its mention in the README
