### ISSUE TITLE
Send an announce to the old Google Group

### ISSUE THREAD

**Issue by rzo1** [apache/incubator-stormcrawler#1172]
We should announce on the old google groups (if they are used), that SC has now joined the incubation at the ASF. Users are encouraged to subscribe to the newly created user@ and/or dev@ lists.

**Comment by jnioche** [comment]
https://incubator.apache.org/projects/stormcrawler.html

There is no user@

**Comment by jnioche** [comment]
the google group is not used anymore
most annoucements have been made on Linkedin
This is not milestone related IMHo

**Comment by jnioche** [comment]
but yes, we can announce on the dead mailing list

**Comment by rzo1** [comment]
Nobody knows, who might wake up ;-) last dead message.

**Comment by jnioche** [comment]
https://groups.google.com/g/digitalpebble/c/QCtHhCQdJEU/m/Ztb4S7HTAAAJ

**Comment by rzo1** [comment]
Thx @jnioche
