### ISSUE TITLE
Build website

### ISSUE THREAD

**Issue by jnioche** [apache/incubator-stormcrawler#1187]
There is currently no ASF website for StormCrawler

https://stormcrawler.net/ points to the pre-ASF site

**Comment by rzo1** [comment]
@pjfanning Can we request a new repository `incubator-stormcrawler-site` for the website? Or is there any restriction on the incubator part for the amount of repos?

As an initial version, we can migrate the content from our "website" branch to it and change it towards ASF requirements. In a next step, we can work on a re-ramp.

**Comment by pjfanning** [comment]
> @pjfanning Can we request a new repository `incubator-stormcrawler-site` for the website? Or is there any restriction on the incubator part for the amount of repos?
> 
> As an initial version, we can migrate the content from our "website" branch to it and change it towards ASF requirements. In a next step, we can work on a re-ramp.

There is no limit on number of repos for incubating projects. Raise an INFRA JIRA. We can create repos using the selfserve tool but this one is special but its content is published to the Apache CDN automatically.

**Comment by rzo1** [comment]
Infra says we can do it ourselves, so will give it a try later.

**Comment by pjfanning** [comment]
We can create the git repo itself - what we can't do is set it up so that its contents are published to the Apache CDN.

https://selfserve.apache.org/

**Comment by rzo1** [comment]
Not via asf.yml? We will see 😁

**Comment by rzo1** [comment]
Seems to work. The migrated source is here https://github.com/apache/incubator-stormcrawler-site/
The website is reachable via https://stormcrawler.apache.org/ and now needs some work regarding:

- Drop 3rd party content (google analytics, ...)
- Migrate resources to be hosted locally, etc.
- Comply with ASF requirements
- Add mailinglists, etc.

**Comment by jnioche** [comment]
thanks @rzo1 
let's track the work needed for the website in https://github.com/apache/incubator-stormcrawler-site/
