### ISSUE TITLE
Documentation Bug: website url in 'Project Info' table is not found

### ISSUE THREAD

**Issue by harikrishna553** [apache/incubator-stormcrawler#1190]
Go to the url https://incubator.apache.org/projects/stormcrawler.html and Click in the reference link against 'Website' item in 'Project Info' table to reproduce the issue

**Comment by jnioche** [comment]
Thanks @harikrishna553 
This is a duplicate of #1187. The link against website will be correct once the website is built

**Comment by rzo1** [comment]
The former website is now migrated and available via https://stormcrawler.apache.org/ - we will address some changes with #1187 to comply with ASF requirements in the near future. Stay tuned :)
