### ISSUE TITLE
Continuing ES use 2.11+

### ISSUE THREAD

**Issue by sam-ulrich1** [apache/incubator-stormcrawler#1191]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the best place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use StackOverflow
       instead with the label 'stormcrawler': https://stackoverflow.com/questions/tagged/stormcrawler 

 - [ ] Bug report. If you’ve found a bug, please include a test if you can, it makes it a lot easier to fix things. Use the label 'bug' on the issue.
 
 - [x ] Feature request. Please use the label 'wish' on the issue.

Thanks!

Please permit the continued use of ES. Migrating clusters may be viable in the future but a minor version jump with the major breaking change of no more ES is difficult to stomach

**Comment by jnioche** [comment]
Hi @sam-ulrich1 (long time no see, I hope you are well)

The next release (and first at Apache) will be a major one so incompatibilities are expected. One of the advantages of SC is its modularity - you could totally piggyback the code for Elastic from previous releases and maintain it in your own repository.

**Comment by sam-ulrich1** [comment]
@jnioche Been well! If anything take it as a compliment that it's been a while. SC has been basically bullet-proof since we last spoke. There's more maintenance on keeping the seed lists good than on the SC deployment!

Currently I am just using the old SC version for the ES plugin and it seems to be working. I definitely get the problem with ES, they really screwed things up. Is the reason y'all are removing because you don't want to maintain compact for both versions?

**Comment by sam-ulrich1** [comment]
Closing since it has been acknowledged that this isn't a priority

**Comment by rzo1** [comment]
@sam-ulrich1 since we are going ASF, WE need to comply with licensing. I.e. we can either stick with an old and outdated version, remove it or ship with optional dependency, so user needs to add the lib.  We did opt for remove.

Nevertheless, the code didn't changed much, so  it is possible to fork that module and maintain it outside the ASF umbrella.
