### ISSUE TITLE
add incubator footer to stormcrawler web site 

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-stormcrawler#1193]
See footer in https://streampark.apache.org/

In Apache Pekko, we were told off for not using the Apache Incubator logo with a white background.

See https://incubator.apache.org/guides/press-kit.html - it has the official white background logo

Also, in the docs we need to say 'Apache StormCrawler (Incubating)' as opposed to just plain  'Apache StormCrawler'.

**Comment by jnioche** [comment]
Tracking in https://github.com/apache/incubator-stormcrawler-site/issues/5

**Comment by jnioche** [comment]
Have added mentions of (Incubating) as part of 

[asf-site b7b1461] Added refs to Incubating + minor fixes to main page. Fixed links in header

**Comment by jnioche** [comment]
The footer has been added
