### ISSUE TITLE
Update Releases Page in GitHub and mark non-ASF releases

### ISSUE THREAD

**Issue by rzo1** [apache/incubator-stormcrawler#1196]
I noticed in some of the incubator vote threads, that people complained about "pre-ASF" releases on other projects.

Since we have those on https://github.com/apache/incubator-stormcrawler/releases too, we can prevent that before doing our first release.

I think, that we have two possibilities:

- (1) Mark every release listed there with a disclaimer like:

> This release was created and published prior to StormCrawler entering incubation at the Apache Software Foundation. Any subsequent developments or changes related to StormCrawler's status within the Apache Software Foundation are not reflected in this release.

- (2) Drop these releases from the overview in GitHub.

WDYT @jnioche @pjfanning ?

**Comment by jnioche** [comment]
I think some users would like to be able to access the old releases, e.g. to get the source of the Elastic module and maintain it separately.
Option 1 would be better, maybe just for the first page of results.
