### ISSUE TITLE
3.0 archetype does not exist (README Instructions)

### ISSUE THREAD

**Issue by joshfischer1108** [apache/incubator-stormcrawler#1205]
Following the README, it states to execute the below to create a new StormCrawler project.  
```
mvn archetype:generate -DarchetypeGroupId=org.apache.stormcrawler -DarchetypeArtifactId=stormcrawler-archetype -DarchetypeVersion=3.0
```
However, the above command results in the below error:
```
[WARNING] The POM for org.apache.stormcrawler:stormcrawler-archetype:jar:3.0 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.292 s
[INFO] Finished at: 2024-05-01T15:35:16-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate (default-cli) on project standalone-pom: The desired archetype does not exist (org.apache.stormcrawler:stormcrawler-archetype:3.0) -> [Help 1]
```

However, the documentation site has the a command that does work (listed below).  I can update the README with this value once we deem it's the right way to correct the documentation.
```
mvn archetype:generate -DarchetypeGroupId=com.digitalpebble.stormcrawler -DarchetypeArtifactId=storm-crawler-archetype -DarchetypeVersion=2.11
```

**Comment by jnioche** [comment]
thanks @joshfischer1108 
The instructions on the README will be correct once we publish our first release at Apache which hopefully will be soon.
Using the old digitalpebble releases is problematic.
What could be done though is to modify the README to add a comment about installing SC with `mvn clean install` then generate from the 3.0-SNAPSHOT archetype. Does that make sense?

**Comment by joshfischer1108** [comment]
Ok, that makes sense.  I will adjust the PR based on your recommendation.
