### ISSUE TITLE
Check license of opensearch/Constants.java

### ISSUE THREAD

**Issue by ayushtkn** [apache/incubator-stormcrawler#1211]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the best place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use StackOverflow
       instead with the label 'stormcrawler': https://stackoverflow.com/questions/tagged/stormcrawler 

 - [ ] Bug report. If you’ve found a bug, please include a test if you can, it makes it a lot easier to fix things. Use the label 'bug' on the issue.
 
 - [ ] Feature request. Please use the label 'wish' on the issue.

Thanks!

The license text seems not very standard :
https://github.com/apache/incubator-stormcrawler/blob/c1088fb3ff3ca9ca99bcce108d8bb2b40b97c094/external/opensearch/src/main/java/org/apache/stormcrawler/opensearch/Constants.java#L2

mentions
```
SPDX-FileCopyrightText: 2022 Presearch SPDX-License-Identifier: Apache-2.0 Licensed to Presearch
```

**Comment by rzo1** [comment]
Yep. Needs a fix. Good finding.
Wonder why Rat didn't spot.
