### ISSUE TITLE
Redirected sitemaps in SiteMapParserBolt / SiteMapFilter

### ISSUE THREAD

**Issue by mvolikas** [apache/incubator-stormcrawler#1230]
Hi!

When the SiteMapParserBolt processes a redirected sitemap that contains links (see for example [http://sample-sitemap.xml](http://www.contexity.ch/sitemap_index.xml)), the [isSitemapKey is added](https://github.com/apache/incubator-stormcrawler/blob/0aad46b5c8a4ebcf455385272d742f8383c64e46/core/src/main/java/org/apache/stormcrawler/bolt/SiteMapParserBolt.java#L148-L150) only after the outlinks have been processed. If the SiteMapFilter is also enabled, then all the links are filtered out since the [SiteMapParserBolt.isSitemapKey is false](https://github.com/apache/incubator-stormcrawler/blob/0aad46b5c8a4ebcf455385272d742f8383c64e46/core/src/main/java/org/apache/stormcrawler/filtering/sitemap/SitemapFilter.java#L53-L54). This is fixed when the `metadata.setValue(isSitemapKey, "true")` is moved before the outlinks processing.

Also, the [sniff](https://github.com/apache/incubator-stormcrawler/blob/0aad46b5c8a4ebcf455385272d742f8383c64e46/core/src/main/java/org/apache/stormcrawler/bolt/SiteMapParserBolt.java#L377) method returns false for some sitemaps, because of the small `maxOffsetGuess`. For example, for this [sitemap](https://www.contexity.ch/post-sitemap.xml). This can be fixed by increasing `sitemap.offset.guess`, however, this might impact performance.

Should I create a PR with the fix for SiteMapParserBolt?
Should I take a shot at a different (efficient) way of "sniffing" a possible sitemap format?

Thanks,
Markos

**Comment by rzo1** [comment]
Feel free to provide a PR with a fix.
We can follow up with a more efficient approach in an additional PR. WDYT?
