### ISSUE TITLE
add DISCLAIMER to jars

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-stormcrawler#1299]
The LICENSE and NOTICE are in the RC jars but not the DISCLAIMER. I'm not sure if it 100% required but many podlings include it.

I checked stormcrawler-core-3.1.0.jar

**Comment by rzo1** [comment]
It is required for release artifacts, which is the source artifact by ASF definition: https://apache.org/legal/release-policy.html#source-packages

Maven artifacts are convenience. I am not aware of an strict incubator policy for this class of files.

**Comment by pjfanning** [comment]
The apache-parent pom.xml appears to have a feature to allow adding a disclaimer to jars. See https://github.com/apache/incubator-xtable/pull/539 (mainly for the code change).
