### ISSUE TITLE
files in jars have odd dates

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-stormcrawler#1300]
I checked the 3.1.0 RC jars and the files in stormcrawler-core-3.1.0.jar all had this date.

07-04-2024

I am in favour of reproducible builds meaning that files in jar may not have today's date but this date is confusing. Many reproducible builds just go with 01-01-1970 dates or some date hardcoded in build but that might reflect some date around the release (as long as the date is hardcoded in the source release so that all builds have this date regardless of when the build with that release is run.

**Comment by rzo1** [comment]
Don't think we set it explicitly, so working towards reproducable builds would be good anyway.

**Comment by pjfanning** [comment]
How did we end up with 7 April or 4 July as the date? (I'm not sure if the date in the file is in International or in US format)

**Comment by rzo1** [comment]
Guess it is a side effect from Apache Parent. Didn't dig into it though.
