### ISSUE TITLE
Update version of StormCrawler in READMEs and archetypes

### ISSUE THREAD

**Issue by jnioche** [apache/incubator-stormcrawler#1317]
The [website](https://stormcrawler.apache.org/getting-started/) also needs fixing

**Comment by rzo1** [comment]
@kunalpal97 would you like to check the website as well for similar occurences?

**Comment by kunalpal97** [comment]
@rzo1  I’d be happy to help! Could you clarify which sections or pages of the website you'd like me to review, or should I go through the entire site?

**Comment by rzo1** [comment]
The Link by @jnioche contains references to the archetype and the Storm version. There might be other occurences as well, maybe a search in an IDE will reveal other locations as well.

**Comment by jnioche** [comment]
For the website here are my notes for the pre-Apache releases, the paths will need changing

```
git checkout gh-pages

point 
[_includes/header.html](https://github.com/DigitalPebble/storm-crawler/edit/gh-pages/_includes/header.html) to latest release

Modify “getting started” as well

[getting-started/index.html](https://github.com/DigitalPebble/storm-crawler/edit/gh-pages/getting-started/index.html)
```

For the READMEs in the repo

```
 README.md
 ./external/warc/README.md  
 ./external/opensearch/README.md
```

I used to `grep -r` on the previous version number to find occurrences.

Thanks @kunalpal97 for offering to contribute

**Comment by jnioche** [comment]
for future reference, changes to the web site are made in https://github.com/apache/incubator-stormcrawler-site

**Comment by jnioche** [comment]
https://github.com/apache/incubator-stormcrawler-site/pull/32
