### ISSUE TITLE
Upgrade dependency Storm 2.6.4

### ISSUE THREAD

**Issue by mvolikas** [apache/incubator-stormcrawler#1323]
The [maven archetype pom](https://github.com/apache/incubator-stormcrawler/blob/main/archetype/src/main/resources/archetype-resources/pom.xml#L35) has `storm.version 2.6.2`. When using this with `stormcrawler-solr` dependency a jetty version incompatibility issue arises. In particular, when submitting the shaded jar to Storm I get:
```
java.lang.IncompatibleClassChangeError:
class org.eclipse.jetty.http.HttpFields$Mutable can not implement org.eclipse.jetty.http.HttpFields,
because it is not an interface (org.eclipse.jetty.http.HttpFields is in unnamed module of loader 'app')
```
This is because Solr 9.6.1 uses Jetty 10.* while Storm 2.6.2 Jetty 9.*. Am I missing something?
When switching to storm 2.6.4 this gets resolved. Given that in storm-crawler 3.1.0 Storm 2.6.4 is used in the [main pom](https://github.com/apache/incubator-stormcrawler/blob/main/pom.xml#L68), maybe we could update the archetype pom to the latest version as well?

**Comment by rzo1** [comment]
Yes. It was missed in the update.

**Comment by jnioche** [comment]
@mvolikas if you write a PR for it, can you please also add a fix for the [core archetype ](archetype/src/main/resources/archetype-resources/pom.xml)? Thanks

**Comment by mvolikas** [comment]
@jnioche I cannot open the link you gave. I guess you mean this [pom](https://github.com/apache/incubator-stormcrawler/blob/main/archetype/src/main/resources/archetype-resources/pom.xml) right? This and the OpenSearch pom are the only places that have version 2.6.2.

**Comment by jnioche** [comment]
> @jnioche I cannot open the link you gave. I guess you mean this [pom](https://github.com/apache/incubator-stormcrawler/blob/main/archetype/src/main/resources/archetype-resources/pom.xml) right? This and the OpenSearch pom are the only places that have version 2.6.2.

yes, not sure where that link came from 
Thanks!
