### ISSUE TITLE
Reinstate support for Elasticsearch now that it's open source again

### ISSUE THREAD

**Issue by cbowdon** [apache/incubator-stormcrawler#1339]
Hi! Thanks for all your work on Stormcrawler, it's fantastically useful.

I appreciate that you removed support for Elasticsearch since it went closed-source. They've now got over their issues with AWS and [returned to a FOSS license (AGPL)](https://www.elastic.co/blog/elasticsearch-is-open-source-again). Would it be possible to add ES back in please?

**Comment by rzo1** [comment]
AGPL is a category x license, cf. https://www.apache.org/legal/resolved.html#category-x which is a license we cannot include in a project under the ASF umbrella.

**Comment by cbowdon** [comment]
Okay, disappointing but I understand. Thanks anyway.

**Comment by rzo1** [comment]
You can just grab the elasticsearch module code before SC was donated to the ASF and put it directly into your project: https://github.com/apache/incubator-stormcrawler/commit/1e0dc43d882318f0209740901a21e3e09ce11a1a

 It is just a matter of copying some classes (the ones you actually need) and adding the necessary ES dependencies and updating imports. The code is still compatible.

**Comment by cbowdon** [comment]
That works. Thanks!
