### ISSUE TITLE
Should I fix some typos in project?

### ISSUE THREAD

**Issue by psxjoy** [apache/incubator-stormcrawler#1354]
What kind of issue is this?

 - [X] Question. This issue tracker is not the best place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use StackOverflow
       instead with the label 'stormcrawler': https://stackoverflow.com/questions/tagged/stormcrawler 

 - [ ] Bug report. If you’ve found a bug, please include a test if you can, it makes it a lot easier to fix things. Use the label 'bug' on the issue.
 
 - [ ] Feature request. Please use the label 'wish' on the issue.

Thanks!
# Description
When I cloned the project and view some apis,I found some typos.
Should I make a PR to fix it? 
I think it will be a great idea for my first contribute to this project.

Feel free assign it to me when you think OK.

**Comment by rzo1** [comment]
Feel free.
