### ISSUE TITLE
Prevent Dependabot from suggesting dependency updates for Jackson

### ISSUE THREAD

**Issue by jnioche** [apache/incubator-stormcrawler#1396]
We need to use whatever Storm uses, which is not necessarily the latestt

See https://github.com/apache/incubator-stormcrawler/pull/1391#issuecomment-2454148742

**Comment by rzo1** [comment]
Here is an example: https://github.com/apache/shiro/blob/main/.github/dependabot.yml

**Comment by dave2wave** [comment]
2.17.3 was released 2 days after 2.18.1 about 2 weeks ago.

Should StormCrawler stay on the exact same version or the same line? EG. Storm is on 2.17.2 while SC is 2.17.3?
