### ISSUE TITLE
Update Tika to 3.0.0

### ISSUE THREAD

**Issue by tballison** [apache/incubator-stormcrawler#1397]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the best place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use StackOverflow
       instead with the label 'stormcrawler': https://stackoverflow.com/questions/tagged/stormcrawler 

 - [ ] Bug report. If you’ve found a bug, please include a test if you can, it makes it a lot easier to fix things. Use the label 'bug' on the issue.
 
 - [ ] Feature request. Please use the label 'wish' on the issue.

- [*] Task. Upgrade dependencies.
Thanks!

I got a clean build locally with Tika 3.0.0 when I removed the aged commons-io version from dependency management. I realize that was there for an older version of hadoop. 

Does a clean build mean that we're good to go, or is it possible that I've just broken everything for hadoop? What other tests should I run (if any)?

**Comment by pjfanning** [comment]
I contribute some dependency upgrades for Hadoop and I don't believe that commons-io presented any issues.

https://mvnrepository.com/artifact/org.apache.hadoop/hadoop-common/3.4.1

That version uses a quite up to date commons-io.

**Comment by pjfanning** [comment]
What I meant is that commons-io seems to maintain good backward compatibility across releases.

**Comment by tballison** [comment]
Sorry. Thank you.

**Comment by tballison** [comment]
:face_palm: this is already done. I hadn't updated my fork in some time. Sorry...
