### ISSUE TITLE
Run the release process for 3.2.0

### ISSUE THREAD

**Issue by tballison** [apache/incubator-stormcrawler#1408]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the best place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use StackOverflow
       instead with the label 'stormcrawler': https://stackoverflow.com/questions/tagged/stormcrawler 

 - [ ] Bug report. If you’ve found a bug, please include a test if you can, it makes it a lot easier to fix things. Use the label 'bug' on the issue.
 
 - [ ] Feature request. Please use the label 'wish' on the issue.
 - [*] Task -- run the release process

First step is select a release manager on the list. I think we did this with: https://lists.apache.org/thread/nfvmfof3l2kgwcqvp4t4h4t4c9v1clo4

**Comment by tballison** [comment]
@rzo1 @jnioche and other fellow devs. What are the diffs I should mention in the email for the 3.2.0 release?

* Updated dependencies
* Numerous bug fixes
* Drop Java-based topologies
* Add support for shards in SolrSpout

**Comment by rzo1** [comment]
Yep sounds got. Maybe mention the websocket option for Playwright protocol. Otherwise, it is mostly the SOLR thing + dependency updates

**Comment by tballison** [comment]
Should we add KEYS to `https://dist.apache.org/repos/dist/dev/` ?

**Comment by rzo1** [comment]
Right. We only vote on source technically, binaries (Maven) are convinience artifacts only.

**Comment by tballison** [comment]
When I update the site, that's a global replace of `3.1.0` to `3.2.0`?

The links will work only once the vote has passed and the artifacts are released, right? Or do I temporarily point the links to the rc1 artifacts?

**Comment by tballison** [comment]
In the vote email, sorry for this, where are the Github release notes? `<Add link to the GitHub release notes>`

I don't actually create the release from https://github.com/apache/incubator-stormcrawler/releases/tag/stormcrawler-3.2.0-rc1 until after the vote, right?

**Comment by rzo1** [comment]
You can create GitHub Release notes on the right site and Mark the release as pre-release or draft.

**Comment by rzo1** [comment]
> When I update the site, that's a global replace of `3.1.0` to `3.2.0`? Anything else?
> 
> The links will work only once the vote has passed and the artifacts are released, right? Or do I temporarily point the links to the rc1 artifacts?

Yes. It is a replacement and a staging deploy manually triggered via starting the related GitHub Action for your Branch with the Site update

**Comment by tballison** [comment]
Thank you @rzo1!

It looks like I should not have included `-rc1` in the tag. If there's a successful vote, I'll rename the tag and update the Github release.

If there's some better way of handling this, let me know.

**Comment by rzo1** [comment]
Should be fine.

**Comment by tballison** [comment]
All set. Thank you, all!
