### ISSUE TITLE
use log4j-bom dependency to ensure that log4j jars match

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-stormcrawler#1436]
The log4j team have told the Apache POI team that they expect all log4j jar versions to match. Some context in https://issues.apache.org/jira/browse/XMLBEANS-654 

The aim is to change the pom in stormcrawler to have a depenendencyManagement declaration to import the log4j-bom.

Eg https://github.com/apache/xmlbeans/commit/9b342d1dc539f59e60806067b3388a32d07ceb85

We would then remove the version from the log4j dependency declarations elsewhere in the pom.

**Comment by rzo1** [comment]
Note: We rely on the version provided by Storm. We can actually remove all references to log4j2 in SC (as we use the one provided by the storm client) which will be available in the Storm Environment.

**Comment by pjfanning** [comment]
Can Storm be updated to use the bom dependency?

**Comment by rzo1** [comment]
> Can Storm be updated to use the bom dependency?

https://github.com/apache/storm/blob/ef493269bda096e6bd03bb70985626a988b70a2d/pom.xml#L802C10-L809C25

**Comment by rzo1** [comment]
Storm is updated, so it gets available with the next version update. Think we can close this here.
