### ISSUE TITLE
Add config to shard based on instance number instead of field

### ISSUE THREAD

**Issue by jnioche** [apache/incubator-stormcrawler#489]
This way all the documents sent by a particular bolt instance would go to the same shard, instead of the request being split and sent to separate nodes then the result aggregated by the coordinating node.

This means that we'd need to have one instance per shard, just like with the spouts and use [URLStreamGrouping](https://github.com/DigitalPebble/storm-crawler/blob/master/core/src/main/java/com/digitalpebble/stormcrawler/util/URLStreamGrouping.java).

The internal cache would still be used as a given URL would be consistently sent to the same bolt instance.

Ideally, we would be able to detect an ideal mapping where local nodes are used if possible.

**Comment by rzo1** [comment]
We dropped ES as we joined the ASF incubator. Closing.
