### ISSUE TITLE
SOLR Status Updater - configure byDomain or byIP

### ISSUE THREAD

**Issue by jnioche** [apache/incubator-stormcrawler#626]
only by host is currently implemented

**Comment by jnioche** [comment]
@mvolikas is that of interest to you?

**Comment by mvolikas** [comment]
I want to give it a try! I'm not 100% sure about the extra functionality we are aiming for though. Is this related to #620? I guess we could start by adding the partition key in the metadata like we do in OpenSearch?

**Comment by jnioche** [comment]
It is exactly that. What this is about it to have the field name to use for the key (and whether it should be in the metadata) configurable, just like in [OpenSearch](https://github.com/apache/incubator-stormcrawler/blob/main/external/opensearch/src/main/java/org/apache/stormcrawler/opensearch/persistence/StatusUpdaterBolt.java#L154) and also add the logic of host/domain/IP .  The logic of how to query based on the shards will be added to the spouts later on in #620
