### ISSUE TITLE
SOLR - add tests using Docker image

### ISSUE THREAD

**Issue by jnioche** [apache/incubator-stormcrawler#851]
Similar to what we have for ES, the tests could spin a Docker container for SOLR and check that documents are indexed as it should be.

**Comment by jnioche** [comment]
See https://www.testcontainers.org/modules/solr/

**Comment by jnioche** [comment]
Initial code in https://github.com/DigitalPebble/storm-crawler/tree/851
Work in progress

**Comment by jnioche** [comment]
@mvolikas since you use this module, any chance you would be able to have a look at this one? Or any of the other [issues for SOLR](https://github.com/apache/incubator-stormcrawler/issues?q=is%3Aissue+is%3Aopen+label%3ASOLR)?

**Comment by mvolikas** [comment]
Sure, thx! I was actually having a look earlier today :)

**Comment by jnioche** [comment]
> Sure, thx! I was actually having a look earlier today :)

That would be fantastic!

**Comment by mvolikas** [comment]
Hi there!
I have opened a PR to branch 851. I fixed the StatusBoltTest and added a very simple IndexerBoltTest (just checks if the tuple is acked). Note that I used a slightly different approach: Now the solr/cores/ configuration files are used for the tests, and the cores are created explicitly. For the Indexer, I could also add a query to Solr that checks that the document is actually in the core. What do you think?

**Comment by jnioche** [comment]
Fixed by #1240
