### ISSUE TITLE
Newer Elasticsearch Version deprecate the REST High Level Client in favour of the Java API Client

### ISSUE THREAD

**Issue by rzo1** [apache/incubator-stormcrawler#945]
The High Level Rest Client is deprecated in favor of the [Elasticsearch Java API Client](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/introduction.html)

This will affect SC, if we want to upgrade Elasticsearch from 7.5.2 to 7.17.0

We should investigate whether the current High Level REST client can be easily replaced by the new Java API client.

A migration guide is available [here](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/migrate-hlrc.html)

**Comment by rzo1** [comment]
@jnioche would have labeld it accordingly, but I do not have  the permissions.

**Comment by jnioche** [comment]
Elasticsearch 8.0 is approaching. We could either port the whole module to 8 and replace the client at the same time or maybe have a new module _elasticsearch-8_ and keep the existing one with HLRC for a bit? We could clean things up a bit at the same time e.g. remove the CollapsingSpout

**Comment by rzo1** [comment]
> The Elasticsearch Java client is forward compatible; meaning that the client supports communicating with greater or equal minor versions of Elasticsearch. Elasticsearch language clients are only backwards compatible with default distributions and without guarantees made. 

I like the `elasticsearch-8` approach as users might have deployed older elasticsearch versions and the HLRC replacement might have an impact, so perhaps we can still update to `7.17.0` (and live with the deprecation warning) and later come up with a `elasticsearch-8` module.

**Comment by jnioche** [comment]
> > The Elasticsearch Java client is forward compatible; meaning that the client supports communicating with greater or equal minor versions of Elasticsearch. Elasticsearch language clients are only backwards compatible with default distributions and without guarantees made.
> 
> I like the `elasticsearch-8` approach as users might have deployed older elasticsearch versions and the HLRC replacement might have an impact, so perhaps we can still update to `7.17.0` (and live with the deprecation warning) and later come up with a `elasticsearch-8` module.

I know quite a few users for whom this would be the case

**Comment by devlperry** [comment]
> Elasticsearch 8 is out! https://www.elastic.co/blog/whats-new-elastic-8-0-0

This related to that? The ES_IndexInit.sh script fails in multiple places. Can't delete metrics* or content* wildcard references, can't use metric* index patterns as it's used by Elastic Agent as per:
https://www.elastic.co/guide/en/elasticsearch/reference/current/index-templates.html
Can disable the builtin templates using stack.templates.enabled, but seems like it would break other features.

**Comment by jnioche** [comment]
thanks @devlperry 
we could have an alternative version of the script in the current module to fix the issues you mentioned when running ES8
any chance you could contribute a PR for this?

**Comment by rzo1** [comment]
We dropped ES, so closing this issue is ok now.
