### ISSUE TITLE
Investigate doc-value-only fields 

### ISSUE THREAD

**Issue by jnioche** [apache/incubator-stormcrawler#957]
https://www.elastic.co/blog/whats-new-elasticsearch-kibana-cloud-8-1-0)](https://www.elastic.co/blog/whats-new-elasticsearch-kibana-cloud-8-1-0

For the _status_ index, only the _key_ and _nextFetchDate_ are frequently queried. Anything else (URL, metadata, status) is mostly used in kibana (unless there is filtering on the source).

Most fields in the _metrics_ would benefit from it.

**Comment by rzo1** [comment]
We dropped ES as we joined the ASF incubator. Closing.
